// Package builtin defines the built-in functions and aggregates in KQL.
package builtin

import (
	"github.com/cloudygreybeard/kqlparser/symbol"
	"github.com/cloudygreybeard/kqlparser/types"
)

// param creates a required parameter.
func param(name string, typ types.Type) *symbol.Parameter {
	return &symbol.Parameter{Name: name, Type: typ}
}

// optParam creates an optional parameter.
func optParam(name string, typ types.Type) *symbol.Parameter {
	return &symbol.Parameter{Name: name, Type: typ, IsOptional: true}
}

// ScalarFunctions contains all built-in scalar functions.
var ScalarFunctions = []*symbol.FunctionSymbol{
	// String functions
	symbol.NewScalarFunction("strlen", types.Typ_Long, param("s", types.Typ_String)),
	symbol.NewScalarFunction("string_size", types.Typ_Long, param("s", types.Typ_String)),
	symbol.NewVariadicFunction("strcat", types.Typ_String, param("s1", types.Typ_String)),
	symbol.NewScalarFunction("strcat_delim", types.Typ_String,
		param("delimiter", types.Typ_String),
		param("s1", types.Typ_String),
		param("s2", types.Typ_String)),
	symbol.NewScalarFunction("strcat_array", types.Typ_String,
		param("array", types.Typ_Dynamic),
		param("delimiter", types.Typ_String)),
	symbol.NewScalarFunction("strcmp", types.Typ_Long,
		param("s1", types.Typ_String),
		param("s2", types.Typ_String)),
	symbol.NewScalarFunction("strrep", types.Typ_String,
		param("value", types.Typ_String),
		param("multiplier", types.Typ_Long),
		optParam("delimiter", types.Typ_String)),
	symbol.NewScalarFunction("substring", types.Typ_String,
		param("source", types.Typ_String),
		param("startIndex", types.Typ_Long),
		optParam("length", types.Typ_Long)),
	symbol.NewScalarFunction("toupper", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("tolower", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("trim", types.Typ_String,
		param("regex", types.Typ_String),
		param("source", types.Typ_String)),
	symbol.NewScalarFunction("trim_start", types.Typ_String,
		param("regex", types.Typ_String),
		param("source", types.Typ_String)),
	symbol.NewScalarFunction("trim_end", types.Typ_String,
		param("regex", types.Typ_String),
		param("source", types.Typ_String)),
	symbol.NewScalarFunction("replace", types.Typ_String,
		param("regex", types.Typ_String),
		param("rewrite", types.Typ_String),
		param("source", types.Typ_String)),
	symbol.NewScalarFunction("replace_string", types.Typ_String,
		param("source", types.Typ_String),
		param("lookup", types.Typ_String),
		param("rewrite", types.Typ_String)),
	symbol.NewScalarFunction("replace_strings", types.Typ_String,
		param("source", types.Typ_String),
		param("lookups", types.Typ_Dynamic),
		param("rewrites", types.Typ_Dynamic)),
	symbol.NewScalarFunction("replace_regex", types.Typ_String,
		param("source", types.Typ_String),
		param("regex", types.Typ_String),
		param("rewrite", types.Typ_String)),
	symbol.NewScalarFunction("split", types.Typ_Dynamic,
		param("source", types.Typ_String),
		param("delimiter", types.Typ_String),
		optParam("requestedIndex", types.Typ_Long)),
	symbol.NewScalarFunction("parse_json", types.Typ_Dynamic, param("json", types.Typ_String)),
	symbol.NewScalarFunction("parsejson", types.Typ_Dynamic, param("json", types.Typ_String)),
	symbol.NewScalarFunction("todynamic", types.Typ_Dynamic, param("json", types.Typ_String)),
	symbol.NewScalarFunction("dynamic_to_json", types.Typ_String, param("dynamic", types.Typ_Dynamic)),
	symbol.NewScalarFunction("tostring", types.Typ_String, param("expr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("extract", types.Typ_String,
		param("regex", types.Typ_String),
		param("captureGroup", types.Typ_Long),
		param("source", types.Typ_String),
		optParam("typeLiteral", types.Typ_String)),
	symbol.NewScalarFunction("extract_all", types.Typ_Dynamic,
		param("regex", types.Typ_String),
		param("source", types.Typ_String)),
	symbol.NewScalarFunction("extractall", types.Typ_Dynamic,
		param("regex", types.Typ_String),
		param("source", types.Typ_String)),
	symbol.NewScalarFunction("extract_json", types.Typ_Dynamic,
		param("jsonPath", types.Typ_String),
		param("source", types.Typ_String)),
	symbol.NewScalarFunction("extractjson", types.Typ_Dynamic,
		param("jsonPath", types.Typ_String),
		param("source", types.Typ_String)),
	symbol.NewScalarFunction("indexof", types.Typ_Long,
		param("source", types.Typ_String),
		param("lookup", types.Typ_String),
		optParam("startIndex", types.Typ_Long),
		optParam("length", types.Typ_Long),
		optParam("occurrence", types.Typ_Long)),
	symbol.NewScalarFunction("indexof_regex", types.Typ_Long,
		param("source", types.Typ_String),
		param("regex", types.Typ_String),
		optParam("startIndex", types.Typ_Long),
		optParam("length", types.Typ_Long),
		optParam("occurrence", types.Typ_Long)),
	symbol.NewScalarFunction("countof", types.Typ_Long,
		param("source", types.Typ_String),
		param("search", types.Typ_String),
		optParam("kind", types.Typ_String)),
	symbol.NewScalarFunction("reverse", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("translate", types.Typ_String,
		param("searchList", types.Typ_String),
		param("replacementList", types.Typ_String),
		param("source", types.Typ_String)),
	symbol.NewScalarFunction("make_string", types.Typ_String, param("args", types.Typ_Dynamic)),
	symbol.NewScalarFunction("regex_quote", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("repeat", types.Typ_Dynamic,
		param("value", types.Typ_Dynamic),
		param("count", types.Typ_Long)),

	// Base64/encoding functions
	symbol.NewScalarFunction("base64_encode_tostring", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("base64_decode_tostring", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("base64_encode_fromarray", types.Typ_String, param("arr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("base64_decode_toarray", types.Typ_Dynamic, param("s", types.Typ_String)),
	symbol.NewScalarFunction("base64_encode_fromguid", types.Typ_String, param("g", types.Typ_Guid)),
	symbol.NewScalarFunction("base64_decode_toguid", types.Typ_Guid, param("s", types.Typ_String)),
	symbol.NewScalarFunction("url_encode", types.Typ_String, param("url", types.Typ_String)),
	symbol.NewScalarFunction("url_encode_component", types.Typ_String, param("url", types.Typ_String)),
	symbol.NewScalarFunction("url_decode", types.Typ_String, param("url", types.Typ_String)),
	symbol.NewScalarFunction("punycode_from_string", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("punycode_to_string", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("punycode_domain_from_string", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("punycode_domain_to_string", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("unicode_codepoints_from_string", types.Typ_Dynamic, param("s", types.Typ_String)),
	symbol.NewScalarFunction("unicode_codepoints_to_string", types.Typ_String, param("arr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("to_utf8", types.Typ_Dynamic, param("s", types.Typ_String)),
	symbol.NewScalarFunction("gzip_compress_to_base64_string", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("gzip_decompress_from_base64_string", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("zlib_compress_to_base64_string", types.Typ_String, param("s", types.Typ_String)),
	symbol.NewScalarFunction("zlib_decompress_from_base64_string", types.Typ_String, param("s", types.Typ_String)),

	// Parse functions
	symbol.NewScalarFunction("parse_csv", types.Typ_Dynamic, param("csv", types.Typ_String)),
	symbol.NewScalarFunction("parse_xml", types.Typ_Dynamic, param("xml", types.Typ_String)),
	symbol.NewScalarFunction("parse_path", types.Typ_Dynamic, param("path", types.Typ_String)),
	symbol.NewScalarFunction("parse_url", types.Typ_Dynamic, param("url", types.Typ_String)),
	symbol.NewScalarFunction("parseurl", types.Typ_Dynamic, param("url", types.Typ_String)),
	symbol.NewScalarFunction("parse_urlquery", types.Typ_Dynamic, param("query", types.Typ_String)),
	symbol.NewScalarFunction("parseurlquery", types.Typ_Dynamic, param("query", types.Typ_String)),
	symbol.NewScalarFunction("parse_version", types.Typ_Decimal, param("version", types.Typ_String)),
	symbol.NewScalarFunction("parse_user_agent", types.Typ_Dynamic, param("userAgent", types.Typ_String)),
	symbol.NewScalarFunction("parse_command_line", types.Typ_Dynamic,
		param("commandLine", types.Typ_String),
		param("type", types.Typ_String)),

	// DateTime functions
	symbol.NewScalarFunction("now", types.Typ_DateTime),
	symbol.NewScalarFunction("ago", types.Typ_DateTime, param("timespan", types.Typ_TimeSpan)),
	symbol.NewScalarFunction("datetime", types.Typ_DateTime, param("value", types.Typ_String)),
	symbol.NewScalarFunction("make_datetime", types.Typ_DateTime,
		param("year", types.Typ_Long),
		optParam("month", types.Typ_Long),
		optParam("day", types.Typ_Long),
		optParam("hour", types.Typ_Long),
		optParam("minute", types.Typ_Long),
		optParam("second", types.Typ_Real)),
	symbol.NewScalarFunction("datetime_add", types.Typ_DateTime,
		param("part", types.Typ_String),
		param("value", types.Typ_Long),
		param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("datetime_diff", types.Typ_Long,
		param("part", types.Typ_String),
		param("datetime1", types.Typ_DateTime),
		param("datetime2", types.Typ_DateTime)),
	symbol.NewScalarFunction("datetime_part", types.Typ_Long,
		param("part", types.Typ_String),
		param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("datepart", types.Typ_Long,
		param("part", types.Typ_String),
		param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("datetime_local_to_utc", types.Typ_DateTime,
		param("datetime", types.Typ_DateTime),
		param("timezone", types.Typ_String)),
	symbol.NewScalarFunction("datetime_utc_to_local", types.Typ_DateTime,
		param("datetime", types.Typ_DateTime),
		param("timezone", types.Typ_String)),
	symbol.NewScalarFunction("datetime_list_timezones", types.Typ_Dynamic),
	symbol.NewScalarFunction("startofday", types.Typ_DateTime,
		param("datetime", types.Typ_DateTime),
		optParam("offset", types.Typ_Long)),
	symbol.NewScalarFunction("startofweek", types.Typ_DateTime,
		param("datetime", types.Typ_DateTime),
		optParam("offset", types.Typ_Long)),
	symbol.NewScalarFunction("startofmonth", types.Typ_DateTime,
		param("datetime", types.Typ_DateTime),
		optParam("offset", types.Typ_Long)),
	symbol.NewScalarFunction("startofyear", types.Typ_DateTime,
		param("datetime", types.Typ_DateTime),
		optParam("offset", types.Typ_Long)),
	symbol.NewScalarFunction("endofday", types.Typ_DateTime,
		param("datetime", types.Typ_DateTime),
		optParam("offset", types.Typ_Long)),
	symbol.NewScalarFunction("endofweek", types.Typ_DateTime,
		param("datetime", types.Typ_DateTime),
		optParam("offset", types.Typ_Long)),
	symbol.NewScalarFunction("endofmonth", types.Typ_DateTime,
		param("datetime", types.Typ_DateTime),
		optParam("offset", types.Typ_Long)),
	symbol.NewScalarFunction("endofyear", types.Typ_DateTime,
		param("datetime", types.Typ_DateTime),
		optParam("offset", types.Typ_Long)),
	symbol.NewScalarFunction("dayofweek", types.Typ_TimeSpan, param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("dayofmonth", types.Typ_Long, param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("dayofyear", types.Typ_Long, param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("weekofyear", types.Typ_Long, param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("week_of_year", types.Typ_Long, param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("monthofyear", types.Typ_Long, param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("hourofday", types.Typ_Long, param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("getyear", types.Typ_Long, param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("getmonth", types.Typ_Long, param("datetime", types.Typ_DateTime)),
	symbol.NewScalarFunction("format_datetime", types.Typ_String,
		param("datetime", types.Typ_DateTime),
		param("format", types.Typ_String)),
	symbol.NewScalarFunction("unixtime_seconds_todatetime", types.Typ_DateTime, param("seconds", types.Typ_Long)),
	symbol.NewScalarFunction("unixtime_milliseconds_todatetime", types.Typ_DateTime, param("ms", types.Typ_Long)),
	symbol.NewScalarFunction("unixtime_microseconds_todatetime", types.Typ_DateTime, param("us", types.Typ_Long)),
	symbol.NewScalarFunction("unixtime_nanoseconds_todatetime", types.Typ_DateTime, param("ns", types.Typ_Long)),

	// Bin functions
	symbol.NewScalarFunction("bin", types.Typ_Dynamic,
		param("value", types.Typ_Dynamic),
		param("roundTo", types.Typ_Dynamic)),
	symbol.NewScalarFunction("bin_at", types.Typ_Dynamic,
		param("value", types.Typ_Dynamic),
		param("bin_size", types.Typ_Dynamic),
		param("fixed_point", types.Typ_Dynamic)),
	symbol.NewScalarFunction("bin_auto", types.Typ_Dynamic, param("value", types.Typ_Dynamic)),

	// TimeSpan functions
	symbol.NewScalarFunction("timespan", types.Typ_TimeSpan, param("value", types.Typ_String)),
	symbol.NewScalarFunction("make_timespan", types.Typ_TimeSpan,
		param("hour", types.Typ_Long),
		optParam("minute", types.Typ_Long),
		optParam("second", types.Typ_Long)),
	symbol.NewScalarFunction("totimespan", types.Typ_TimeSpan, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("totime", types.Typ_TimeSpan, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("format_timespan", types.Typ_String,
		param("timespan", types.Typ_TimeSpan),
		param("format", types.Typ_String)),

	// Math functions
	symbol.NewScalarFunction("abs", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("ceil", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("ceiling", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("floor", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("round", types.Typ_Real,
		param("x", types.Typ_Real),
		optParam("precision", types.Typ_Long)),
	symbol.NewScalarFunction("sqrt", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("pow", types.Typ_Real, param("base", types.Typ_Real), param("exp", types.Typ_Real)),
	symbol.NewScalarFunction("log", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("log10", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("log2", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("loggamma", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("exp", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("exp10", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("exp2", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("gamma", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("erf", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("erfc", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("beta_cdf", types.Typ_Real,
		param("x", types.Typ_Real),
		param("alpha", types.Typ_Real),
		param("beta", types.Typ_Real)),
	symbol.NewScalarFunction("beta_inv", types.Typ_Real,
		param("probability", types.Typ_Real),
		param("alpha", types.Typ_Real),
		param("beta", types.Typ_Real)),
	symbol.NewScalarFunction("beta_pdf", types.Typ_Real,
		param("x", types.Typ_Real),
		param("alpha", types.Typ_Real),
		param("beta", types.Typ_Real)),
	symbol.NewScalarFunction("sin", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("cos", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("tan", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("cot", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("asin", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("acos", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("atan", types.Typ_Real, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("atan2", types.Typ_Real, param("y", types.Typ_Real), param("x", types.Typ_Real)),
	symbol.NewScalarFunction("degrees", types.Typ_Real, param("radians", types.Typ_Real)),
	symbol.NewScalarFunction("radians", types.Typ_Real, param("degrees", types.Typ_Real)),
	symbol.NewScalarFunction("pi", types.Typ_Real),
	symbol.NewScalarFunction("sign", types.Typ_Long, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("rand", types.Typ_Real, optParam("n", types.Typ_Long)),
	symbol.NewScalarFunction("isnan", types.Typ_Bool, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("isinf", types.Typ_Bool, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("isfinite", types.Typ_Bool, param("x", types.Typ_Real)),
	symbol.NewScalarFunction("min_of", types.Typ_Dynamic, param("args", types.Typ_Dynamic)),
	symbol.NewScalarFunction("max_of", types.Typ_Dynamic, param("args", types.Typ_Dynamic)),
	symbol.NewScalarFunction("welch_test", types.Typ_Real,
		param("mean1", types.Typ_Real),
		param("variance1", types.Typ_Real),
		param("count1", types.Typ_Long),
		param("mean2", types.Typ_Real),
		param("variance2", types.Typ_Real),
		param("count2", types.Typ_Long)),

	// Binary/bitwise functions
	symbol.NewScalarFunction("binary_and", types.Typ_Long, param("a", types.Typ_Long), param("b", types.Typ_Long)),
	symbol.NewScalarFunction("binary_or", types.Typ_Long, param("a", types.Typ_Long), param("b", types.Typ_Long)),
	symbol.NewScalarFunction("binary_xor", types.Typ_Long, param("a", types.Typ_Long), param("b", types.Typ_Long)),
	symbol.NewScalarFunction("binary_not", types.Typ_Long, param("a", types.Typ_Long)),
	symbol.NewScalarFunction("binary_shift_left", types.Typ_Long,
		param("value", types.Typ_Long),
		param("shift", types.Typ_Long)),
	symbol.NewScalarFunction("binary_shift_right", types.Typ_Long,
		param("value", types.Typ_Long),
		param("shift", types.Typ_Long)),
	symbol.NewScalarFunction("bitset_count_ones", types.Typ_Long, param("value", types.Typ_Long)),
	symbol.NewScalarFunction("tohex", types.Typ_String,
		param("value", types.Typ_Long),
		optParam("minLength", types.Typ_Long)),

	// Type conversion
	symbol.NewScalarFunction("toint", types.Typ_Int, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("tolong", types.Typ_Long, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("todouble", types.Typ_Real, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("toreal", types.Typ_Real, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("todecimal", types.Typ_Decimal, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("tobool", types.Typ_Bool, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("toboolean", types.Typ_Bool, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("todatetime", types.Typ_DateTime, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("toguid", types.Typ_Guid, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("toobject", types.Typ_Dynamic, param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("gettype", types.Typ_String, param("expr", types.Typ_Dynamic)),

	// Null/empty handling
	symbol.NewScalarFunction("isnull", types.Typ_Bool, param("expr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("isnotnull", types.Typ_Bool, param("expr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("notnull", types.Typ_Dynamic, param("expr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("isempty", types.Typ_Bool, param("expr", types.Typ_String)),
	symbol.NewScalarFunction("isnotempty", types.Typ_Bool, param("expr", types.Typ_String)),
	symbol.NewScalarFunction("notempty", types.Typ_String, param("expr", types.Typ_String)),
	symbol.NewScalarFunction("isascii", types.Typ_Bool, param("s", types.Typ_String)),
	symbol.NewScalarFunction("isutf8", types.Typ_Bool, param("s", types.Typ_String)),
	symbol.NewScalarFunction("coalesce", types.Typ_Dynamic,
		param("expr1", types.Typ_Dynamic),
		param("expr2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("iff", types.Typ_Dynamic,
		param("condition", types.Typ_Bool),
		param("ifTrue", types.Typ_Dynamic),
		param("ifFalse", types.Typ_Dynamic)),
	symbol.NewScalarFunction("iif", types.Typ_Dynamic,
		param("condition", types.Typ_Bool),
		param("ifTrue", types.Typ_Dynamic),
		param("ifFalse", types.Typ_Dynamic)),
	symbol.NewScalarFunction("case", types.Typ_Dynamic,
		param("condition", types.Typ_Bool),
		param("result", types.Typ_Dynamic)),
	symbol.NewScalarFunction("assert", types.Typ_Bool,
		param("condition", types.Typ_Bool),
		param("message", types.Typ_String)),

	// Format functions
	symbol.NewScalarFunction("format_bytes", types.Typ_String,
		param("bytes", types.Typ_Long),
		optParam("precision", types.Typ_Long),
		optParam("base", types.Typ_Long)),
	symbol.NewScalarFunction("estimate_data_size", types.Typ_Long, param("columns", types.Typ_Dynamic)),

	// Column functions
	symbol.NewScalarFunction("column_ifexists", types.Typ_Dynamic,
		param("columnName", types.Typ_String),
		param("defaultValue", types.Typ_Dynamic)),
	symbol.NewScalarFunction("columnifexists", types.Typ_Dynamic,
		param("columnName", types.Typ_String),
		param("defaultValue", types.Typ_Dynamic)),
	symbol.NewScalarFunction("column_names_of", types.Typ_Dynamic, param("table", types.Typ_String)),

	// Row functions
	symbol.NewScalarFunction("row_number", types.Typ_Long),
	symbol.NewScalarFunction("row_cumsum", types.Typ_Real,
		param("expr", types.Typ_Real),
		optParam("restart", types.Typ_Bool)),
	symbol.NewScalarFunction("row_rank", types.Typ_Long, param("expr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("row_rank_dense", types.Typ_Long, param("expr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("row_rank_min", types.Typ_Long, param("expr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("row_window_session", types.Typ_DateTime,
		param("expr", types.Typ_DateTime),
		param("maxIdleTime", types.Typ_TimeSpan),
		param("maxWindowSize", types.Typ_TimeSpan),
		optParam("restart", types.Typ_Bool)),
	symbol.NewScalarFunction("prev", types.Typ_Dynamic,
		param("column", types.Typ_Dynamic),
		optParam("offset", types.Typ_Long),
		optParam("defaultValue", types.Typ_Dynamic)),
	symbol.NewScalarFunction("next", types.Typ_Dynamic,
		param("column", types.Typ_Dynamic),
		optParam("offset", types.Typ_Long),
		optParam("defaultValue", types.Typ_Dynamic)),

	// Table/database functions
	symbol.NewScalarFunction("table", types.Typ_Dynamic, param("tableName", types.Typ_String)),
	symbol.NewScalarFunction("external_table", types.Typ_Dynamic, param("tableName", types.Typ_String)),
	symbol.NewScalarFunction("materialized_view", types.Typ_Dynamic, param("viewName", types.Typ_String)),
	symbol.NewScalarFunction("cluster", types.Typ_String, param("clusterName", types.Typ_String)),
	symbol.NewScalarFunction("database", types.Typ_String, optParam("databaseName", types.Typ_String)),
	symbol.NewScalarFunction("current_database", types.Typ_String),
	symbol.NewScalarFunction("stored_query_result", types.Typ_Dynamic, param("name", types.Typ_String)),

	// Array/Dynamic functions
	symbol.NewScalarFunction("array_length", types.Typ_Long, param("arr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("arraylength", types.Typ_Long, param("arr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("array_concat", types.Typ_Dynamic,
		param("arr1", types.Typ_Dynamic),
		param("arr2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("array_index_of", types.Typ_Long,
		param("arr", types.Typ_Dynamic),
		param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("array_slice", types.Typ_Dynamic,
		param("arr", types.Typ_Dynamic),
		param("start", types.Typ_Long),
		param("end", types.Typ_Long)),
	symbol.NewScalarFunction("array_split", types.Typ_Dynamic,
		param("arr", types.Typ_Dynamic),
		param("indices", types.Typ_Dynamic)),
	symbol.NewScalarFunction("array_sum", types.Typ_Real, param("arr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("array_sort_asc", types.Typ_Dynamic,
		param("arr", types.Typ_Dynamic),
		optParam("nullsFirst", types.Typ_Bool)),
	symbol.NewScalarFunction("array_sort_desc", types.Typ_Dynamic,
		param("arr", types.Typ_Dynamic),
		optParam("nullsFirst", types.Typ_Bool)),
	symbol.NewScalarFunction("array_reverse", types.Typ_Dynamic, param("arr", types.Typ_Dynamic)),
	symbol.NewScalarFunction("array_rotate_left", types.Typ_Dynamic,
		param("arr", types.Typ_Dynamic),
		param("rotate", types.Typ_Long)),
	symbol.NewScalarFunction("array_rotate_right", types.Typ_Dynamic,
		param("arr", types.Typ_Dynamic),
		param("rotate", types.Typ_Long)),
	symbol.NewScalarFunction("array_shift_left", types.Typ_Dynamic,
		param("arr", types.Typ_Dynamic),
		param("shift", types.Typ_Long),
		optParam("fill", types.Typ_Dynamic)),
	symbol.NewScalarFunction("array_shift_right", types.Typ_Dynamic,
		param("arr", types.Typ_Dynamic),
		param("shift", types.Typ_Long),
		optParam("fill", types.Typ_Dynamic)),
	symbol.NewScalarFunction("array_iff", types.Typ_Dynamic,
		param("condition", types.Typ_Dynamic),
		param("ifTrue", types.Typ_Dynamic),
		param("ifFalse", types.Typ_Dynamic)),
	symbol.NewScalarFunction("array_iif", types.Typ_Dynamic,
		param("condition", types.Typ_Dynamic),
		param("ifTrue", types.Typ_Dynamic),
		param("ifFalse", types.Typ_Dynamic)),
	symbol.NewScalarFunction("array_strcat", types.Typ_String,
		param("arr", types.Typ_Dynamic),
		param("delimiter", types.Typ_String)),
	symbol.NewScalarFunction("set_difference", types.Typ_Dynamic,
		param("set1", types.Typ_Dynamic),
		param("set2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("set_has_element", types.Typ_Bool,
		param("set", types.Typ_Dynamic),
		param("element", types.Typ_Dynamic)),
	symbol.NewScalarFunction("set_intersect", types.Typ_Dynamic,
		param("set1", types.Typ_Dynamic),
		param("set2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("set_union", types.Typ_Dynamic,
		param("set1", types.Typ_Dynamic),
		param("set2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("set_equals", types.Typ_Bool,
		param("set1", types.Typ_Dynamic),
		param("set2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("jaccard_index", types.Typ_Real,
		param("set1", types.Typ_Dynamic),
		param("set2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("zip", types.Typ_Dynamic,
		param("arr1", types.Typ_Dynamic),
		param("arr2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("pack", types.Typ_Dynamic),
	symbol.NewScalarFunction("pack_all", types.Typ_Dynamic),
	symbol.NewScalarFunction("pack_array", types.Typ_Dynamic, param("args", types.Typ_Dynamic)),
	symbol.NewScalarFunction("pack_dictionary", types.Typ_Dynamic, param("args", types.Typ_Dynamic)),
	symbol.NewScalarFunction("bag_keys", types.Typ_Dynamic, param("bag", types.Typ_Dynamic)),
	symbol.NewScalarFunction("bag_has_key", types.Typ_Bool,
		param("bag", types.Typ_Dynamic),
		param("key", types.Typ_String)),
	symbol.NewScalarFunction("bag_merge", types.Typ_Dynamic,
		param("bag1", types.Typ_Dynamic),
		param("bag2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("bag_pack", types.Typ_Dynamic, param("args", types.Typ_Dynamic)),
	symbol.NewScalarFunction("bag_pack_columns", types.Typ_Dynamic),
	symbol.NewScalarFunction("bag_remove_keys", types.Typ_Dynamic,
		param("bag", types.Typ_Dynamic),
		param("keys", types.Typ_Dynamic)),
	symbol.NewScalarFunction("bag_set_key", types.Typ_Dynamic,
		param("bag", types.Typ_Dynamic),
		param("key", types.Typ_String),
		param("value", types.Typ_Dynamic)),
	symbol.NewScalarFunction("bag_zip", types.Typ_Dynamic,
		param("keys", types.Typ_Dynamic),
		param("values", types.Typ_Dynamic)),
	symbol.NewScalarFunction("treepath", types.Typ_Dynamic, param("dynamic", types.Typ_Dynamic)),

	// IP functions
	symbol.NewScalarFunction("parse_ipv4", types.Typ_Long, param("ip", types.Typ_String)),
	symbol.NewScalarFunction("parse_ipv4_mask", types.Typ_Long,
		param("ip", types.Typ_String),
		param("prefix", types.Typ_Long)),
	symbol.NewScalarFunction("parse_ipv6", types.Typ_String, param("ip", types.Typ_String)),
	symbol.NewScalarFunction("parse_ipv6_mask", types.Typ_String,
		param("ip", types.Typ_String),
		param("prefix", types.Typ_Long)),
	symbol.NewScalarFunction("format_ipv4", types.Typ_String,
		param("ip", types.Typ_Dynamic),
		optParam("prefix", types.Typ_Long)),
	symbol.NewScalarFunction("format_ipv4_mask", types.Typ_String,
		param("ip", types.Typ_Dynamic),
		param("prefix", types.Typ_Long)),
	symbol.NewScalarFunction("ipv4_compare", types.Typ_Long,
		param("ip1", types.Typ_String),
		param("ip2", types.Typ_String),
		optParam("prefix", types.Typ_Long)),
	symbol.NewScalarFunction("ipv4_is_match", types.Typ_Bool,
		param("ip1", types.Typ_String),
		param("ip2", types.Typ_String),
		optParam("prefix", types.Typ_Long)),
	symbol.NewScalarFunction("ipv4_is_in_range", types.Typ_Bool,
		param("ip", types.Typ_String),
		param("range", types.Typ_String)),
	symbol.NewScalarFunction("ipv4_is_in_any_range", types.Typ_Bool,
		param("ip", types.Typ_String),
		param("ranges", types.Typ_Dynamic)),
	symbol.NewScalarFunction("ipv4_is_private", types.Typ_Bool, param("ip", types.Typ_String)),
	symbol.NewScalarFunction("ipv4_netmask_suffix", types.Typ_Long, param("ip", types.Typ_String)),
	symbol.NewScalarFunction("ipv4_range_to_cidr_list", types.Typ_Dynamic,
		param("startIp", types.Typ_String),
		param("endIp", types.Typ_String)),
	symbol.NewScalarFunction("ipv6_compare", types.Typ_Long,
		param("ip1", types.Typ_String),
		param("ip2", types.Typ_String),
		optParam("prefix", types.Typ_Long)),
	symbol.NewScalarFunction("ipv6_is_match", types.Typ_Bool,
		param("ip1", types.Typ_String),
		param("ip2", types.Typ_String),
		optParam("prefix", types.Typ_Long)),
	symbol.NewScalarFunction("ipv6_is_in_range", types.Typ_Bool,
		param("ip", types.Typ_String),
		param("range", types.Typ_String)),
	symbol.NewScalarFunction("ipv6_is_in_any_range", types.Typ_Bool,
		param("ip", types.Typ_String),
		param("ranges", types.Typ_Dynamic)),
	symbol.NewScalarFunction("has_ipv4", types.Typ_Bool,
		param("source", types.Typ_String),
		param("ip", types.Typ_String)),
	symbol.NewScalarFunction("has_ipv4_prefix", types.Typ_Bool,
		param("source", types.Typ_String),
		param("ipPrefix", types.Typ_String)),
	symbol.NewScalarFunction("has_any_ipv4", types.Typ_Bool,
		param("source", types.Typ_String),
		param("ips", types.Typ_Dynamic)),
	symbol.NewScalarFunction("has_any_ipv4_prefix", types.Typ_Bool,
		param("source", types.Typ_String),
		param("ipPrefixes", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_info_from_ip_address", types.Typ_Dynamic, param("ip", types.Typ_String)),

	// Hash functions
	symbol.NewScalarFunction("hash", types.Typ_Long, param("source", types.Typ_Dynamic)),
	symbol.NewScalarFunction("hash_sha256", types.Typ_String, param("source", types.Typ_String)),
	symbol.NewScalarFunction("hash_md5", types.Typ_String, param("source", types.Typ_String)),

	// GUID functions
	symbol.NewScalarFunction("new_guid", types.Typ_Guid),
	symbol.NewScalarFunction("guid", types.Typ_Guid, param("value", types.Typ_String)),

	// Geo functions
	symbol.NewScalarFunction("geo_point_to_s2cell", types.Typ_String,
		param("longitude", types.Typ_Real),
		param("latitude", types.Typ_Real),
		optParam("level", types.Typ_Long)),
	symbol.NewScalarFunction("geo_s2cell_to_central_point", types.Typ_Dynamic, param("s2cell", types.Typ_String)),
	symbol.NewScalarFunction("geo_s2cell_to_polygon", types.Typ_Dynamic, param("s2cell", types.Typ_String)),
	symbol.NewScalarFunction("geo_s2cell_neighbors", types.Typ_Dynamic, param("s2cell", types.Typ_String)),
	symbol.NewScalarFunction("geo_point_to_geohash", types.Typ_String,
		param("longitude", types.Typ_Real),
		param("latitude", types.Typ_Real),
		optParam("accuracy", types.Typ_Long)),
	symbol.NewScalarFunction("geo_geohash_to_central_point", types.Typ_Dynamic, param("geohash", types.Typ_String)),
	symbol.NewScalarFunction("geo_geohash_to_polygon", types.Typ_Dynamic, param("geohash", types.Typ_String)),
	symbol.NewScalarFunction("geo_geohash_neighbors", types.Typ_Dynamic, param("geohash", types.Typ_String)),
	symbol.NewScalarFunction("geo_point_to_h3cell", types.Typ_String,
		param("longitude", types.Typ_Real),
		param("latitude", types.Typ_Real),
		optParam("resolution", types.Typ_Long)),
	symbol.NewScalarFunction("geo_h3cell_to_central_point", types.Typ_Dynamic, param("h3cell", types.Typ_String)),
	symbol.NewScalarFunction("geo_h3cell_to_polygon", types.Typ_Dynamic, param("h3cell", types.Typ_String)),
	symbol.NewScalarFunction("geo_h3cell_neighbors", types.Typ_Dynamic, param("h3cell", types.Typ_String)),
	symbol.NewScalarFunction("geo_h3cell_level", types.Typ_Long, param("h3cell", types.Typ_String)),
	symbol.NewScalarFunction("geo_h3cell_parent", types.Typ_String,
		param("h3cell", types.Typ_String),
		optParam("resolution", types.Typ_Long)),
	symbol.NewScalarFunction("geo_h3cell_children", types.Typ_Dynamic,
		param("h3cell", types.Typ_String),
		optParam("resolution", types.Typ_Long)),
	symbol.NewScalarFunction("geo_h3cell_rings", types.Typ_Dynamic,
		param("h3cell", types.Typ_String),
		param("distance", types.Typ_Long)),
	symbol.NewScalarFunction("geo_distance_2points", types.Typ_Real,
		param("p1_longitude", types.Typ_Real),
		param("p1_latitude", types.Typ_Real),
		param("p2_longitude", types.Typ_Real),
		param("p2_latitude", types.Typ_Real)),
	symbol.NewScalarFunction("geo_distance_point_to_line", types.Typ_Real,
		param("longitude", types.Typ_Real),
		param("latitude", types.Typ_Real),
		param("line", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_distance_point_to_polygon", types.Typ_Real,
		param("longitude", types.Typ_Real),
		param("latitude", types.Typ_Real),
		param("polygon", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_point_in_circle", types.Typ_Bool,
		param("longitude", types.Typ_Real),
		param("latitude", types.Typ_Real),
		param("centerLongitude", types.Typ_Real),
		param("centerLatitude", types.Typ_Real),
		param("radius", types.Typ_Real)),
	symbol.NewScalarFunction("geo_point_in_polygon", types.Typ_Bool,
		param("longitude", types.Typ_Real),
		param("latitude", types.Typ_Real),
		param("polygon", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_polygon_area", types.Typ_Real, param("polygon", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_polygon_perimeter", types.Typ_Real, param("polygon", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_polygon_centroid", types.Typ_Dynamic, param("polygon", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_polygon_buffer", types.Typ_Dynamic,
		param("polygon", types.Typ_Dynamic),
		param("radius", types.Typ_Real)),
	symbol.NewScalarFunction("geo_polygon_densify", types.Typ_Dynamic,
		param("polygon", types.Typ_Dynamic),
		optParam("tolerance", types.Typ_Real)),
	symbol.NewScalarFunction("geo_polygon_simplify", types.Typ_Dynamic,
		param("polygon", types.Typ_Dynamic),
		param("tolerance", types.Typ_Real)),
	symbol.NewScalarFunction("geo_polygon_to_s2cells", types.Typ_Dynamic,
		param("polygon", types.Typ_Dynamic),
		optParam("level", types.Typ_Long)),
	symbol.NewScalarFunction("geo_polygon_to_h3cells", types.Typ_Dynamic,
		param("polygon", types.Typ_Dynamic),
		optParam("resolution", types.Typ_Long)),
	symbol.NewScalarFunction("geo_line_length", types.Typ_Real, param("line", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_line_centroid", types.Typ_Dynamic, param("line", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_line_buffer", types.Typ_Dynamic,
		param("line", types.Typ_Dynamic),
		param("radius", types.Typ_Real)),
	symbol.NewScalarFunction("geo_line_densify", types.Typ_Dynamic,
		param("line", types.Typ_Dynamic),
		optParam("tolerance", types.Typ_Real)),
	symbol.NewScalarFunction("geo_line_simplify", types.Typ_Dynamic,
		param("line", types.Typ_Dynamic),
		param("tolerance", types.Typ_Real)),
	symbol.NewScalarFunction("geo_line_to_s2cells", types.Typ_Dynamic,
		param("line", types.Typ_Dynamic),
		optParam("level", types.Typ_Long)),
	symbol.NewScalarFunction("geo_point_buffer", types.Typ_Dynamic,
		param("longitude", types.Typ_Real),
		param("latitude", types.Typ_Real),
		param("radius", types.Typ_Real)),
	symbol.NewScalarFunction("geo_from_wkt", types.Typ_Dynamic, param("wkt", types.Typ_String)),
	symbol.NewScalarFunction("geo_angle", types.Typ_Real,
		param("p1", types.Typ_Dynamic),
		param("p2", types.Typ_Dynamic),
		param("p3", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_azimuth", types.Typ_Real,
		param("p1_longitude", types.Typ_Real),
		param("p1_latitude", types.Typ_Real),
		param("p2_longitude", types.Typ_Real),
		param("p2_latitude", types.Typ_Real)),
	symbol.NewScalarFunction("geo_intersects_2lines", types.Typ_Bool,
		param("line1", types.Typ_Dynamic),
		param("line2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_intersects_2polygons", types.Typ_Bool,
		param("polygon1", types.Typ_Dynamic),
		param("polygon2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_intersects_line_with_polygon", types.Typ_Bool,
		param("line", types.Typ_Dynamic),
		param("polygon", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_intersection_2lines", types.Typ_Dynamic,
		param("line1", types.Typ_Dynamic),
		param("line2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_intersection_2polygons", types.Typ_Dynamic,
		param("polygon1", types.Typ_Dynamic),
		param("polygon2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_intersection_line_with_polygon", types.Typ_Dynamic,
		param("line", types.Typ_Dynamic),
		param("polygon", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_union_lines_array", types.Typ_Dynamic, param("lines", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_union_polygons_array", types.Typ_Dynamic, param("polygons", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_simplify_polygons_array", types.Typ_Dynamic,
		param("polygons", types.Typ_Dynamic),
		param("tolerance", types.Typ_Real)),
	symbol.NewScalarFunction("geo_closest_point_on_line", types.Typ_Dynamic,
		param("longitude", types.Typ_Real),
		param("latitude", types.Typ_Real),
		param("line", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_closest_point_on_polygon", types.Typ_Dynamic,
		param("longitude", types.Typ_Real),
		param("latitude", types.Typ_Real),
		param("polygon", types.Typ_Dynamic)),
	symbol.NewScalarFunction("geo_line_locate_point", types.Typ_Real,
		param("line", types.Typ_Dynamic),
		param("longitude", types.Typ_Real),
		param("latitude", types.Typ_Real)),
	symbol.NewScalarFunction("geo_line_interpolate_point", types.Typ_Dynamic,
		param("line", types.Typ_Dynamic),
		param("fraction", types.Typ_Real)),

	// Special functions
	symbol.NewScalarFunction("current_principal", types.Typ_String),
	symbol.NewScalarFunction("current_principal_details", types.Typ_Dynamic),
	symbol.NewScalarFunction("current_principal_is_member_of", types.Typ_Bool, param("groups", types.Typ_Dynamic)),
	symbol.NewScalarFunction("current_cluster_endpoint", types.Typ_String),
	symbol.NewScalarFunction("ingestion_time", types.Typ_DateTime),
	symbol.NewScalarFunction("cursor_after", types.Typ_Bool, param("cursor", types.Typ_String)),
	symbol.NewScalarFunction("cursor_before_or_at", types.Typ_Bool, param("cursor", types.Typ_String)),
	symbol.NewScalarFunction("cursor_current", types.Typ_String),
	symbol.NewScalarFunction("current_cursor", types.Typ_String),
	symbol.NewScalarFunction("extent_id", types.Typ_Guid),
	symbol.NewScalarFunction("extentid", types.Typ_Guid),
	symbol.NewScalarFunction("extent_tags", types.Typ_Dynamic),
	symbol.NewScalarFunction("has_any_index", types.Typ_Long,
		param("source", types.Typ_String),
		param("lookups", types.Typ_Dynamic)),
}

// Aggregates contains all built-in aggregate functions.
var Aggregates = []*symbol.AggregateSymbol{
	symbol.NewAggregate("count", types.Typ_Long),
	symbol.NewAggregate("countif", types.Typ_Long, param("predicate", types.Typ_Bool)),
	symbol.NewAggregate("dcount", types.Typ_Long,
		param("expr", types.Typ_Dynamic),
		optParam("accuracy", types.Typ_Long)),
	symbol.NewAggregate("dcountif", types.Typ_Long,
		param("expr", types.Typ_Dynamic),
		param("predicate", types.Typ_Bool)),

	symbol.NewAggregate("sum", types.Typ_Real, param("expr", types.Typ_Real)),
	symbol.NewAggregate("sumif", types.Typ_Real,
		param("expr", types.Typ_Real),
		param("predicate", types.Typ_Bool)),
	symbol.NewAggregate("avg", types.Typ_Real, param("expr", types.Typ_Real)),
	symbol.NewAggregate("avgif", types.Typ_Real,
		param("expr", types.Typ_Real),
		param("predicate", types.Typ_Bool)),

	symbol.NewAggregate("min", types.Typ_Dynamic, param("expr", types.Typ_Dynamic)),
	symbol.NewAggregate("minif", types.Typ_Dynamic,
		param("expr", types.Typ_Dynamic),
		param("predicate", types.Typ_Bool)),
	symbol.NewAggregate("max", types.Typ_Dynamic, param("expr", types.Typ_Dynamic)),
	symbol.NewAggregate("maxif", types.Typ_Dynamic,
		param("expr", types.Typ_Dynamic),
		param("predicate", types.Typ_Bool)),

	symbol.NewAggregate("stdev", types.Typ_Real, param("expr", types.Typ_Real)),
	symbol.NewAggregate("stdevp", types.Typ_Real, param("expr", types.Typ_Real)),
	symbol.NewAggregate("variance", types.Typ_Real, param("expr", types.Typ_Real)),
	symbol.NewAggregate("variancep", types.Typ_Real, param("expr", types.Typ_Real)),

	symbol.NewAggregate("percentile", types.Typ_Real,
		param("expr", types.Typ_Real),
		param("percentile", types.Typ_Real)),
	symbol.NewAggregate("percentiles", types.Typ_Dynamic,
		param("expr", types.Typ_Real),
		param("percentiles", types.Typ_Dynamic)),
	symbol.NewAggregate("percentiles_array", types.Typ_Dynamic,
		param("expr", types.Typ_Real),
		param("percentiles", types.Typ_Dynamic)),

	symbol.NewAggregate("make_list", types.Typ_Dynamic,
		param("expr", types.Typ_Dynamic),
		optParam("maxSize", types.Typ_Long)),
	symbol.NewAggregate("make_list_if", types.Typ_Dynamic,
		param("expr", types.Typ_Dynamic),
		param("predicate", types.Typ_Bool)),
	symbol.NewAggregate("make_set", types.Typ_Dynamic,
		param("expr", types.Typ_Dynamic),
		optParam("maxSize", types.Typ_Long)),
	symbol.NewAggregate("make_set_if", types.Typ_Dynamic,
		param("expr", types.Typ_Dynamic),
		param("predicate", types.Typ_Bool)),
	symbol.NewAggregate("make_bag", types.Typ_Dynamic,
		param("expr", types.Typ_Dynamic),
		optParam("maxSize", types.Typ_Long)),
	symbol.NewAggregate("make_bag_if", types.Typ_Dynamic,
		param("expr", types.Typ_Dynamic),
		param("predicate", types.Typ_Bool)),

	symbol.NewAggregate("any", types.Typ_Dynamic, param("expr", types.Typ_Dynamic)),
	symbol.NewAggregate("anyif", types.Typ_Dynamic,
		param("expr", types.Typ_Dynamic),
		param("predicate", types.Typ_Bool)),
	symbol.NewAggregate("take_any", types.Typ_Dynamic, param("expr", types.Typ_Dynamic)),
	symbol.NewAggregate("take_anyif", types.Typ_Dynamic,
		param("expr", types.Typ_Dynamic),
		param("predicate", types.Typ_Bool)),

	symbol.NewAggregate("arg_max", types.Typ_Dynamic,
		param("exprToMaximize", types.Typ_Dynamic),
		param("exprToReturn", types.Typ_Dynamic)),
	symbol.NewAggregate("arg_min", types.Typ_Dynamic,
		param("exprToMinimize", types.Typ_Dynamic),
		param("exprToReturn", types.Typ_Dynamic)),

	symbol.NewAggregate("binary_all_and", types.Typ_Long, param("expr", types.Typ_Long)),
	symbol.NewAggregate("binary_all_or", types.Typ_Long, param("expr", types.Typ_Long)),
	symbol.NewAggregate("binary_all_xor", types.Typ_Long, param("expr", types.Typ_Long)),

	symbol.NewAggregate("hll", types.Typ_Dynamic,
		param("expr", types.Typ_Dynamic),
		optParam("accuracy", types.Typ_Long)),
	symbol.NewAggregate("hll_merge", types.Typ_Dynamic, param("hll", types.Typ_Dynamic)),
	symbol.NewAggregate("tdigest", types.Typ_Dynamic, param("expr", types.Typ_Real)),
	symbol.NewAggregate("tdigest_merge", types.Typ_Dynamic, param("tdigest", types.Typ_Dynamic)),

	// Statistical aggregates
	symbol.NewAggregate("buildschema", types.Typ_Dynamic, param("expr", types.Typ_Dynamic)),
}

// SeriesFunctions contains series analysis functions.
var SeriesFunctions = []*symbol.FunctionSymbol{
	symbol.NewScalarFunction("series_abs", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_add", types.Typ_Dynamic,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_subtract", types.Typ_Dynamic,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_multiply", types.Typ_Dynamic,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_divide", types.Typ_Dynamic,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_equals", types.Typ_Dynamic,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_not_equals", types.Typ_Dynamic,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_less", types.Typ_Dynamic,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_less_equals", types.Typ_Dynamic,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_greater", types.Typ_Dynamic,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_greater_equals", types.Typ_Dynamic,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_sum", types.Typ_Real, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_product", types.Typ_Real, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_sign", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_floor", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_ceiling", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_exp", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_log", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_pow", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		param("exponent", types.Typ_Real)),
	symbol.NewScalarFunction("series_sin", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_cos", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_tan", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_asin", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_acos", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_atan", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_magnitude", types.Typ_Real, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_dot_product", types.Typ_Real,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_cosine_similarity", types.Typ_Real,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_pearson_correlation", types.Typ_Real,
		param("series1", types.Typ_Dynamic),
		param("series2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_stats", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_stats_dynamic", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_fit_line", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_fit_line_dynamic", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_fit_2lines", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_fit_2lines_dynamic", types.Typ_Dynamic, param("series", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_fit_poly", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		param("degree", types.Typ_Long)),
	symbol.NewScalarFunction("series_outliers", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		optParam("kind", types.Typ_String),
		optParam("ignoreVal", types.Typ_Real)),
	symbol.NewScalarFunction("series_decompose", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		optParam("seasonality", types.Typ_Long),
		optParam("trend", types.Typ_String)),
	symbol.NewScalarFunction("series_decompose_anomalies", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		optParam("threshold", types.Typ_Real)),
	symbol.NewScalarFunction("series_decompose_forecast", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		param("points", types.Typ_Long)),
	symbol.NewScalarFunction("series_seasonal", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		optParam("seasonality", types.Typ_Long)),
	symbol.NewScalarFunction("series_periods_detect", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		param("minPeriod", types.Typ_Real),
		param("maxPeriod", types.Typ_Real),
		param("numPeriods", types.Typ_Long)),
	symbol.NewScalarFunction("series_periods_validate", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		param("periods", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_fill_backward", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		optParam("missingValuePlaceholder", types.Typ_Real)),
	symbol.NewScalarFunction("series_fill_forward", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		optParam("missingValuePlaceholder", types.Typ_Real)),
	symbol.NewScalarFunction("series_fill_const", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		optParam("constantValue", types.Typ_Real),
		optParam("missingValuePlaceholder", types.Typ_Real)),
	symbol.NewScalarFunction("series_fill_linear", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		optParam("missingValuePlaceholder", types.Typ_Real)),
	symbol.NewScalarFunction("series_fir", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		param("filter", types.Typ_Dynamic),
		optParam("normalize", types.Typ_Bool)),
	symbol.NewScalarFunction("series_iir", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		param("numerators", types.Typ_Dynamic),
		param("denominators", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_fft", types.Typ_Dynamic,
		param("series", types.Typ_Dynamic),
		optParam("imaginary", types.Typ_Dynamic)),
	symbol.NewScalarFunction("series_ifft", types.Typ_Dynamic,
		param("real", types.Typ_Dynamic),
		optParam("imaginary", types.Typ_Dynamic)),

	// tdigest/hll scalar functions
	symbol.NewScalarFunction("dcount_hll", types.Typ_Long, param("hll", types.Typ_Dynamic)),
	symbol.NewScalarFunction("hll_isvalid", types.Typ_Bool, param("hll", types.Typ_Dynamic)),
	symbol.NewScalarFunction("tdigest_isvalid", types.Typ_Bool, param("tdigest", types.Typ_Dynamic)),
	symbol.NewScalarFunction("percentile_tdigest", types.Typ_Real,
		param("tdigest", types.Typ_Dynamic),
		param("percentile", types.Typ_Real)),
	symbol.NewScalarFunction("percentiles_array_tdigest", types.Typ_Dynamic,
		param("tdigest", types.Typ_Dynamic),
		param("percentiles", types.Typ_Dynamic)),
	symbol.NewScalarFunction("percentrank_tdigest", types.Typ_Real,
		param("tdigest", types.Typ_Dynamic),
		param("value", types.Typ_Real)),
	symbol.NewScalarFunction("merge_tdigest", types.Typ_Dynamic,
		param("tdigest1", types.Typ_Dynamic),
		param("tdigest2", types.Typ_Dynamic)),
	symbol.NewScalarFunction("rank_tdigest", types.Typ_Long,
		param("tdigest", types.Typ_Dynamic),
		param("value", types.Typ_Real)),
}

// DefaultScope returns a scope with all built-in functions and aggregates.
func DefaultScope() *symbol.Scope {
	scope := symbol.NewScope(nil)
	for _, fn := range ScalarFunctions {
		scope.Define(fn)
	}
	for _, fn := range SeriesFunctions {
		scope.Define(fn)
	}
	for _, agg := range Aggregates {
		scope.Define(agg)
	}
	return scope
}
